# Generated by Django 5.2.13 on 2026-06-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10, verbose_name='Секция')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('flat_id', models.CharField(max_length=50, verbose_name='ID / номер квартиры')),
                ('path_d', models.TextField(verbose_name='SVG path (d)')),
            ],
            options={
                'verbose_name': 'Полигон квартиры',
                'verbose_name_plural': 'Полигоны квартир',
                'ordering': ('section', 'floor', 'flat_id'),
                'unique_together': {('section', 'floor', 'flat_id')},
            },
        ),
    ]
