# Generated by Django 5.2.13 on 2026-06-29 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccordionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(default='Внутри проекта · Инфраструктура', max_length=200, verbose_name='Kicker')),
                ('title', models.CharField(default='Дом, который', max_length=200, verbose_name='Заголовок')),
                ('title_accent', models.CharField(default='раскрывается', max_length=60, verbose_name='Акцентное слово (курсив)')),
            ],
            options={
                'verbose_name': 'Аккордеон-секция',
                'verbose_name_plural': 'Аккордеон-секция',
            },
        ),
        migrations.CreateModel(
            name='ApplySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(default='Заявка', max_length=60, verbose_name='Kicker')),
                ('title', models.CharField(default='Запишитесь на', max_length=120, verbose_name='Заголовок')),
                ('title_accent', models.CharField(default='приватный показ', max_length=60, verbose_name='Акцентное слово (курсив)')),
                ('subtitle', models.TextField(default='Оставьте контакты — менеджер свяжется с вами и подберёт удобное время визита в шоурум.', verbose_name='Подзаголовок')),
                ('success_title', models.CharField(default='Спасибо', max_length=60, verbose_name='Заголовок успеха')),
                ('success_text', models.CharField(default='Заявка принята. Мы свяжемся с вами в ближайшее время.', max_length=200, verbose_name='Текст успеха')),
            ],
            options={
                'verbose_name': 'Форма заявки',
                'verbose_name_plural': 'Форма заявки',
            },
        ),
        migrations.CreateModel(
            name='EditorialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Архитектура вне времени', max_length=120, verbose_name='Заголовок')),
                ('cta_text', models.CharField(default='Выбрать квартиру', max_length=60, verbose_name='Текст кнопки')),
                ('cta_link', models.CharField(default='/flats', max_length=200, verbose_name='Ссылка кнопки')),
            ],
            options={
                'verbose_name': 'Editorial-секция',
                'verbose_name_plural': 'Editorial-секция',
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Жилой комплекс премиум-класса. Архитектура, продуманная для жизни.', max_length=200, verbose_name='Слоган')),
                ('office_address', models.CharField(default='Офис продаж: г. Уфа, ул. Гафури, 77', max_length=200, verbose_name='Адрес офиса')),
                ('work_hours', models.CharField(default='ЕЖЕДНЕВНО с 10:00 до 20:00', max_length=100, verbose_name='Время работы')),
                ('phone', models.CharField(default='+7 (347) 225 70 25', max_length=30, verbose_name='Телефон')),
                ('map_address', models.CharField(default='г. Уфа, ул. Менделеева, 154', max_length=200, verbose_name='Адрес на карте')),
                ('map_url', models.URLField(default='https://yandex.ru/maps/172/ufa/house/ulitsa_mendeleyeva_154/YU8YdgViT0QCQFtufXtzcXhiZw==/', max_length=500, verbose_name='Ссылка на карту')),
                ('copyright_text', models.CharField(default='© 2026 МАКСИМУС. Все права защищены.', max_length=120, verbose_name='Копирайт')),
                ('vk_url', models.URLField(blank=True, default='https://vk.com/gk_stroitek_ufa', max_length=300, verbose_name='ВКонтакте')),
                ('telegram_url', models.URLField(blank=True, default='https://t.me/gk_stroitek_ufa', max_length=300, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Подвал',
                'verbose_name_plural': 'Подвал',
            },
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(default='Архитектура · Горизонт', max_length=200, verbose_name='Kicker')),
            ],
            options={
                'verbose_name': 'Галерея-секция',
                'verbose_name_plural': 'Галерея-секция',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Жилой комплекс · I очередь', max_length=120, verbose_name='Надпись сверху')),
                ('title', models.CharField(default='МАКСИМУС', max_length=60, verbose_name='Заголовок')),
                ('subtitle', models.CharField(default='Архитектура премиум-класса на берегу города', max_length=200, verbose_name='Подзаголовок')),
                ('background_image', models.ImageField(blank=True, upload_to='hero/', verbose_name='Фоновое изображение')),
            ],
            options={
                'verbose_name': 'Hero-секция',
                'verbose_name_plural': 'Hero-секция',
            },
        ),
        migrations.CreateModel(
            name='VideoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Не менять', unique=True, verbose_name='Идентификатор')),
                ('video', models.FileField(blank=True, upload_to='video/', verbose_name='Видео')),
                ('eyebrow', models.CharField(blank=True, max_length=200, verbose_name='Надпись сверху')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('cta_text', models.CharField(blank=True, max_length=60, verbose_name='Текст кнопки')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок на странице')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Видео-блок',
                'verbose_name_plural': 'Видео-блоки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AccordionPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, verbose_name='Метка (таб)')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='accordion/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, upload_to='accordion/', verbose_name='Видео')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='content.accordionsection')),
            ],
            options={
                'verbose_name': 'Панель',
                'verbose_name_plural': 'Панели',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EditorialPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='editorial/', verbose_name='Фото')),
                ('number', models.CharField(default='01', max_length=4, verbose_name='Номер')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.editorialsection')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EditorialFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='content.editorialsection')),
            ],
            options={
                'verbose_name': 'Фича',
                'verbose_name_plural': 'Фичи',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GallerySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, verbose_name='Метка')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='content.gallerysection')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VideoBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.videoblock')),
            ],
            options={
                'verbose_name': 'Пункт',
                'verbose_name_plural': 'Пункты',
                'ordering': ['order'],
            },
        ),
    ]
